### ISSUE TITLE
Loading iframe as a single file

### ISSUE THREAD

**Issue by masylum** [gildas-lormeau/single-file-core#3]
Hello there! I have a question I couldn't figure out the answer: Can I use `single-file-core` to take the contents of an iframe and convert it into a single file? The use case is that I want to cache iframes in OPFS, so next time you load the page, you can see the contents of the iframe from OPFS (so it works offline). I'm currently using the single-file CLI to download the page on a background job, but if I could do this on the client it would be fantastic. Thanks in advance!

**Comment by gildas-lormeau** [comment]
Did you solve the issue yourself?
